spring:
  application:
    name: spring-cloud-kubernetes-config-demo
  cloud:
    kubernetes:
      config:
        enable-api: true
        enabled: true
        name: ${spring.application.name}
        namespace: default
      reload:
        monitoring-config-maps: true
        enabled: true
        strategy: refresh
external:
  config: "application.yml!"
logging:
  level:
    org.springframework: DEBUG
