apiVersion: v1
kind: ConfigMap
metadata:
#  matches the spring app name as defined in application.yml
  name: spring-cloud-kubernetes-config-demo
data:
#  must be named 'application.yaml' or be the only key in this config
#  refer to Spring Cloud Kubernetes Config documentation or source code
  application.yaml: |-
    app:
      config: Configuration from Kubernetes!

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-variable-config
data:
  ENVIRONMENT_CONFIG: Configuration from Docker environment in Kubernetes!
